name: AI Blockfeed Harvester

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # elke dag om 08:00 UTC

jobs:
  harvester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: .  # Zorgt dat de repo direct in de root staat

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug current directory
        run: |
          pwd
          ls -R

      - name: Run harvester
        run: python src/main.py

      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockfeed-output
          path: output/
