name: AI Blockfeed Harvester

on:
  schedule:
    - cron: '0 8 * * *'   # elke dag om 08:00 UTC
  workflow_dispatch:       

jobs:
  harvester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run harvester
        run: python src/main.py

      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockfeed-output
          path: output/ 
